### ISSUE TITLE
初次学习想请教一下关于spm2的命令

### ISSUE THREAD

**Issue by ch-hui** [spmjs/spm2#100]
我运行spm -help为什么只有System Commands和Package Commands，之前文档上面有提到过的init和build命令哪里去了？及时是在安装了插件之后还是没有办法识别命令。
![image](https://f.cloud.github.com/assets/4827119/1507932/1d3248c6-49be-11e3-8de7-7e88a1c52df1.png)

**Comment by afc163** [comment]
init 和 build 都是插件提供的功能。

http://docs.spmjs.org/cli/init
http://docs.spmjs.org/cli/build

如果运行了命令还是没有注册上，把 npm install spm-build -g 的 log 信息贴出来看看有什么问题。
