### ISSUE TITLE
grunt-cmd-concat 在合并代码的时候如何重写css中的url(**/*.**)?

### ISSUE THREAD

**Issue by eggao** [spmjs/spm2#101]
项目使用grunt打包。在提取依赖，合并依赖之后css是直接写入到页面中的。如何重写css样式中的图片等资源的地址呢？

**Comment by jiangyuan** [comment]
这个其实很简单的，可能 @eggao 没有发现。
可以自定义一个任务，将 url(**/*.**) 批量替换成你想要的任务。
可以用 grunt.file.read 和 grunt.file.write 接口。
如果你有用 grunt-contrib-copy ，他有个 processContent 回调函数……

**Comment by popomore** [comment]
其实和 concat 没关系，在 concat 之前先处理下 css。
