### ISSUE TITLE
请更新一下angularjs版本

### ISSUE THREAD

**Issue by zicjin** [spmjs/spm2#103]
版本更新速度太滞后了。

**Comment by afc163** [comment]
把 spmjs.org 的账号给下吧，我让@leoner 给你开个 publish 权限，因为我们自己用的很少，你可以帮我们一起更新。

**Comment by edokeh** [comment]
1.2 也才发布了一周左右嘛

**Comment by zicjin** [comment]
zicjin@gmail.com

**Comment by zicjin** [comment]
@edokeh 从三个月前rc版开始就一直放在 http://angularjs.org 的默认下载位了。可能各人对rc版本的想法不同吧。

**Comment by edokeh** [comment]
1.2 才是 stable ，之前的一个 stable 版本其实是 1.0.8，1.1.5 都不算
我觉得作为中央库还是保守一点比较好，虽然其实我也用了好久 1.2-rc2 。。。

**Comment by edokeh** [comment]
@afc163 
我看了下 Spm 仓库中 angular 的封装，觉得还有更好的方式，尤其是对 angular-cookies,angular-resource 这些 angular module

现在的方式，是在这些 module 的代码外层包裹一个 define 函数，并且加入 require('angular') ，但是没有 exports
https://github.com/cmdjs/angular/blob/master/angularjs/Gruntfile.js#L15

这样的封装，会造成用 Sea.js 写 angular 代码时，需要这样

```
var angular = require('angular');
require('angular-resource');

var app = angular.module('app', ['resource']);

```

这样存在两个问题，一是存在有副作用的 require（因为没有返回值），二是申明 module 的依赖时，需要用字符串，容易出错（手写代码是万恶之源）

如果在封装时，能输出定义的 angular module ，那么代码可以这样写了

```
var angular = require('angular');
var angularResource = require('angular-resource');

var app = angular.module('app', [angularResource.name]);
```

看起来舒服很多，而且即使依赖的部分写错了，编辑器直接就能报警

**Comment by leoner** [comment]
如果有更好的方式，更好呀，原来的那个也是当时找到的一个解决方式，但是后续由于没有再用了，所以没有继续优化呀。

**Comment by edokeh** [comment]
那我发个 PR 到 CMDJS 那边呗
还有最新的 1.2.1 好像还是没上到 Spm 仓库？

**Comment by leoner** [comment]
恩， 那你发过来后， 我就给发上去呀

**Comment by afc163** [comment]
给他们加上 spmjs.org 上的发布权限吧。

**Comment by leoner** [comment]
@zicjin 已发布 1.2.3. 你看下能用否？

**Comment by edokeh** [comment]
@leoner 
Angular 1.2 包含的模块多了不少，看这里
http://docs.angularjs.org/api
http://code.angularjs.org/1.2.3/  
现在 spm 上的至少还缺 animate, route, sanitize, touch

发 PR 时以为你们会补上，所以我偷了个懒，结果。。。

**Comment by leoner** [comment]
@edokeh 晕，好吧，那要不你在 PR 下，我再发布下呀。

**Comment by leoner** [comment]
当时没有注意。

**Comment by leoner** [comment]
好了，发布了，@edokeh 你在试下呀。

**Comment by edokeh** [comment]
有缓存？
https://spmjs.org/repository/angular/angularjs/1.2.3/angularjs-1.2.3.tar.gz
这个地址下载下来依然只有 cookie 和 resource 两个包

**Comment by leoner** [comment]
@edokeh sorry. 你在试下

**Comment by edokeh** [comment]
已OK！
