### ISSUE TITLE
.spmrc设置了format后install的组件的依赖路径不正确

### ISSUE THREAD

**Issue by larry4xie** [spmjs/spm2#105]
### file .spmrc

[install]
format = {{family}}/{{name}}/{{filename}}
### base-debug.js

![image](https://f.cloud.github.com/assets/1777254/1645300/faf58c3e-58fc-11e3-9277-fc157be2db23.png)

如上图，filename都不正确

**Comment by popomore** [comment]
看看依赖的 class 和 events 文件

**Comment by larry4xie** [comment]
![image](https://f.cloud.github.com/assets/1777254/1650325/565ace08-5a7f-11e3-93e5-e068d67ced1a.png)

**Comment by popomore** [comment]
猜测：你把  class 和 events 拷贝到相对路径，但源码 require 的时候并不是 `./`

**Comment by larry4xie** [comment]
@popomore  我是直接spm install arale/base 安装到目录下的代码就是这样的（前提是我配置了format）

**Comment by popomore** [comment]
是个 bug
