### ISSUE TITLE
 transport:css 处理建议

### ISSUE THREAD

**Issue by zzhdi** [spmjs/spm2#108]
起因：
 package.json

<pre><code>
...
"output":["a.js","a.css","a.png"]
...
</code></pre>

a.js

<pre><code>
define(function(require, exports, module) {    
    require("./a.css");
....
</code></pre>

a.css

<pre><code>
....
background: url(a.png) no-repeat;
...
</code></pre>

使用 spm build 后，
a-debug.js

<pre><code>
define(...,function(){
     ...
     require("a-debug.css");
     .....
});

define("...", [], function() {    seajs.importStyle("..
   background:url(a.png) no-repeat}");
});
</code></pre>

运行时，导致图片加载错误。

建议：1.如果配置了css输出，能否不对css 进行 transport（即不生成 -debug.js 文件中的第二个define代码块
2、如果没有配置css输出，生成第二个define代码块，能否同时对图片路径进行修正？

**Comment by popomore** [comment]
我的方案图片是绝对地址，所以这种场景是不考虑的。

你可以通过使用 grunt 组织自己的方案。

PS: 如果有 css 的相对引用就会打包进来，并且转换成 cmd 模块。配置 css 的 output 是会同时输出一个 css 文件。
