### ISSUE TITLE
谈一个关于grunt-init的问题。

### ISSUE THREAD

**Issue by hellolibo** [spmjs/spm2#11]
使用grunt-init的 writePackageJSON方法写文件，似乎只能写他们指定的项目，我增加spm中的family 它都过滤掉了，如何处理这个问题？ 让package.json做为一个文件模板？还是专门为spm定义一个json文件?

**Comment by popomore** [comment]
目前输入的 family 会写在最下面，后续会覆盖下这个方法 spmjs/spm-init#1

**Comment by hellolibo** [comment]
没有发现写在最下面吗，直接过滤了，最终的package.js时没有family这项

**Comment by lepture** [comment]
@hellolibo 使用 spm init

https://github.com/spmjs/spm-init
https://github.com/aralejs/template-arale/tree/spm2

**Comment by lepture** [comment]
@hellolibo 关闭，该 issue 在 spmjs/spm-init#1 中讨论。
