### ISSUE TITLE
spm@2.5 坑位

### ISSUE THREAD

**Issue by afc163** [spmjs/spm2#110]
It is time to be better.

---
## 现存的问题（先简单描述下）
1. 订死的目录结构，不够灵活。
2. CMD 书写规范，在业界现有的 github 模块中不通用。
3. spm build 和 dist 目录都不是必要的。
4. family 属性应该在 spm 字段里面。
## 本次升级的愿景
1. 可以给现有的业界模块 pull request ，通过简单的添加 spm 字段，就可以发布到 spmjs.org 。
2. 现有的 arale 模块改造为 CommonJS 的写法，可以继续方便的本地调试。
3. 兼容 spm@2.1。

**Comment by leoner** [comment]
赞
