### ISSUE TITLE
有没有网页可以查看目前所有的模块，比如 npmjs.org 这样的

### ISSUE THREAD

**Issue by hbrls** [spmjs/spm2#113]
`spm search` 太抽象了，都不知道自己该搜什么，不如能一个个看过来

**Comment by popomore** [comment]
https://spmjs.org/

**Comment by hbrls** [comment]
这个还是只能 search 啊，有么有分类列表之类的，刚才的例子举的不好，比如这样的 https://nodejsmodules.org/

**Comment by lizzie** [comment]
可以搜索框里搜 family name, 列出此 family 下的所有模块, 目前还没有 list 页面
