### ISSUE TITLE
spm 2.0.0 发布日志

### ISSUE THREAD

**Issue by lepture** [spmjs/spm2#12]
> 这不是愚人节玩笑，spm 2.0 终于发布了。

首先申明一下 **spm 不是构建工具**，spm 是包管理器。作为一个包管理器，它的主要任务是管理包，也就是管理 cmd 模块。

同时我们的[源服务网站](https://spmjs.org/)也步入 alpha 了，功能还未完善，我们将在使用中进步。spm 的主要任务即是与源服务打交道，包括获取模块信息(spm info)、搜索模块(spm search)、下载模块(spm install)、上传模块(spm publish)等。

当然，并不是说 spm 就不做构建了，它将负责 cmd 标准模块的构建。业务代码的构建方案请参考 [grunt-spm-build](https://github.com/spmjs/grunt-spm-build)，同时，关于构建的 issue 请不要提到 [spm2](https://github.com/spmjs/spm2) 里来，请提到 grunt-spm-build。

我们的文档网站是 http://docs.spmjs.org 。目前文档还在写作中，欢迎[帮助完善文档](https://github.com/spmjs/docs.spmjs.org)。
## grunt

关于自定义构建，我们推荐使用 grunt。我们为你提供了一些 task (这些 task 也用于 spm build)：
- [grunt-cmd-transport](https://github.com/spmjs/grunt-cmd-transport)
- [grunt-cmd-concat](https://github.com/spmjs/grunt-cmd-concat)
## plugins

你可以安装插件来扩展 spm 的命令，我们已发布了：
- [spm-init](https://github.com/spmjs/spm-init)
- [spm-status](https://github.com/spmjs/spm-status)
## 安装与使用

获取 spm 2.0：

```
$ npm install spm -g
```

使用 spm：

```
$ spm -h
```

你还可以查看一下演示（录制较早，部分功能略有不同）： http://ascii.io/a/2533
## seajs

seajs 2.0 发布日志：https://github.com/seajs/seajs/issues/451

**Comment by yyy651016236** [comment]
提问：使用spm install gallery/jquery@1.8.2报错是怎么回事?之前一直是好好的，google了半天没找到原因。
        install: gallery/jquery@1.8.2
        fetch: gallery/jquery@1.8.2
        yuan: not found
        warn: not in cache
        clone: git://github.com/gallery/jquery.git
        execute: git clone git://github.com/gallery/jquery.git $CWD.spm\src\gallery\jquery
        error: Command failed: fatal: could not create work tree dir '$CWD.spm\src\gallery\jquery'.: No such file or directory

**Comment by lepture** [comment]
@yyy651016236 

```
spm search jquery
```

```
spm info jquery
```

```
spm info jquery/jquery
```

**Comment by yyy651016236** [comment]
谢谢！以前的地址不能用了吗？只能先searche？

**Comment by lepture** [comment]
@yyy651016236 jquery is now located at `jquery/jquery`

https://spmjs.org/jquery/

**Comment by lichunqiang** [comment]
spm版本2.1.10
环境是是windows。
我使用

``` javascript
spm search jquery
```

报错了：

``` python
error: { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
```

我使用

``` python
spm install seajs/seajs
```

能成功，但是安装如jquery则失败，问题同上。

**Comment by differui** [comment]
我照着[文档](http://docs.spmjs.org/en/index)在试：

```
spm install
```

提示：`json: ENOENT, no such file or directory '$CWD\package.json'`
可是当前目录下面明明放着package.json，何故？

**Comment by differui** [comment]
解决了：
之前改了注册表，使得在运行命令行的时候能 autorun 到指定的目录 - desktop。导致在安装包的时候虽然已经切换到需要的目录，但是结果却安装在 desktop 。将注册表中的 `autorun` 移除,问题解决。
