### ISSUE TITLE
win7 64bit安装spm错误

### ISSUE THREAD

**Issue by wdong18** [spmjs/spm2#120]
win7 64bit安装spm，在nodejs命令行下运行
npm install spm -g
提示错误：
2319 error Error: ENOENT, lstat 'C:\Users\itoware.ITOWARE-WANGDON\AppData\Roaming\npm\node_modules\node_modules\spm\node_modules\form-data\node_modules\combined-stream\test\fixture\file2.txt'
2320 error If you need help, you may report this log at:
2320 error     http://github.com/isaacs/npm/issues
2320 error or email it to:
2320 error     npm-@googlegroups.com
2321 error System Windows_NT 6.1.7601
2322 error command "D:\Program Files\nodejs\\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "spm" "-g"
2323 error cwd D:\Users\Itoware
2324 error node -v v0.10.12
2325 error npm -v 1.2.32
2326 error path C:\Users\itoware.ITOWARE-WANGDON\AppData\Roaming\npm\node_modules\node_modules\spm\node_modules\form-data\node_modules\combined-stream\test\fixture\file2.txt
2327 error fstream_path C:\Users\itoware.ITOWARE-WANGDON\AppData\Roaming\npm\node_modules\node_modules\spm\node_modules\form-data\node_modules\combined-stream\test\fixture\file2.txt
2328 error fstream_type File
2329 error fstream_class FileWriter
2330 error code ENOENT
2331 error errno 34
2332 error fstream_stack D:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
2332 error fstream_stack Object.oncomplete (fs.js:107:15)
2333 verbose exit [ 34, true ]

**Comment by afc163** [comment]
先尝试升级下 node 和 npm 。

**Comment by dreamstu** [comment]
我的也报错了，不知道是什么原因！
![qq20140630143252](https://cloud.githubusercontent.com/assets/6358099/3426399/8aefbe16-0020-11e4-830d-bf7e4cb6e8b5.png)

**Comment by dreamstu** [comment]
`os：win7 x64`
`node v0.10.29`
`npm v1.4.14`

**Comment by sorrycc** [comment]
奇怪，这个 preinstall.js 怎么是从当前路径开始找的? 建议用官方的 msi 包重装下 node 试试。

**Comment by dreamstu** [comment]
恩，在这之前，我就是用nodejs.org网站的msi安装的。刚刚安装的。

**Comment by sorrycc** [comment]
找了台 x64 的 win7 试了下，重现不了。。
