### ISSUE TITLE
spm所有插件的中心仓库在哪里？

### ISSUE THREAD

**Issue by shownhei** [spmjs/spm2#122]
Q1:spm install XXX的时候是在哪里去下载的？

Q2:spm install gallery 我发现以前的项目里面也有gallery这个东西，但是不知道是来做什么的。

**Comment by afc163** [comment]
spm@2.x 的默认源地址是 https://spmjs.org
spm@3.x 的默认源地址是 http://spmjs.io

**Comment by shownhei** [comment]
谢谢，找的就是这个，gallery什么东西呢。

**Comment by afc163** [comment]
不知道你本地是 spm2 还是 spm3，如果是 spm2 的话，gallery 是指一个 family。https://spmjs.org/gallery/

http://docs.spmjs.org/doc/package#family-required

你本地的 gallery 是啥，我就不知道了。

**Comment by shownhei** [comment]
thank you ,看了下gallery里面的插件，一下就明白了
