### ISSUE TITLE
auto update

### ISSUE THREAD

**Issue by lepture** [spmjs/spm2#14]
自动检查更新。

在 `.spm/autoupdate` 里记录最后检查时间，每周检查一次更新。

```
GET http://spmjs.org/repository/software.json
```

返回：

```
{
  "name": "spm",
  "version": "2.0.0"
}
```

比较当前版本与源里的版本大小，如果小于源所要求的版本，则提示更新。

**Comment by tonyc726** [comment]
@lepture 
如果需要自动提示的话，是需要在`.spm`下配置`config.json`么？
提示后自动更新需要如何实现呢？
