### ISSUE TITLE
spmjs.org中的项目还比较少

### ISSUE THREAD

**Issue by lileiseven** [spmjs/spm2#18]
搜索了下jquery还只1.8.0版本，arale / alice 也不全。 这个2.0发布的貌似有点着急。

**Comment by afc163** [comment]
spm2 发布和 arale alice 没有直接联系，这是供整个互联网使用的源托管服务。

很快 arale 和 alice 都会迁移到 spmjs.org 上。

**Comment by popomore** [comment]
spm 发布了大家才能往上传么。

**Comment by tonyc726** [comment]
spm2 上的jquery，应该是没有转换过的吧？
另外 `jquery/jquery` 这样的目录有点疑惑啊？不知道它属属于`lib`还是`gallery`的？

**Comment by hellolibo** [comment]
@tonyc620  我也很好奇jquery下面再jquery，而不是在gallery里，这样是出于什么考虑的。

**Comment by lepture** [comment]
@hellolibo https://spmjs.org/jquery/

**Comment by hellolibo** [comment]
明白了，我的处理是jquery 目录再加一个 jquery-plugin 目录
