### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by imeoer** [spmjs/spm2#19]
``` js
require('spm').install({
    query: ['underscore'],
    destination: './'
}, function() {
    console.info('install success!');
});
```

报错，应该是目的地址不正确.

**Comment by lepture** [comment]
@imeoer 

```
        install: underscore/underscore
          fetch: underscore/underscore
           yuan: not found
           warn: not in cache
          clone: git://github.com/underscore/underscore.git
        execute: git clone git://github.com/underscore/underscore.git ~/.spm/src/underscore/underscore
          error: Command failed: fatal: remote error:
  Repository not found.
```

这样的错误？

`query: ['gallery/underscore']`

**Comment by imeoer** [comment]
@lepture 这样子：

install: documentcloud/backbone
  fetch: documentcloud/backbone
   yuan: not found
   warn: not in cache
  clone: git://github.com/documentcloud/backbone.git
execute: git clone git://github.com/documentcloud/backbone.git C:\Users\iMeoer.spm\src\documentcloud\backbone
  error: Command failed: fatal: could not create work tree dir 'C:\Users\iMeoer.spm\src\documentcloud\backbone'.: No such file or directory

**Comment by imeoer** [comment]
![ Q -20130407111334](https://f.cloud.github.com/assets/1524576/348202/2d784a9c-9f31-11e2-959e-26333aa4d8e0.png)
@lepture

**Comment by lepture** [comment]
@imeoer `spm install gallery/backbone` now.

**Comment by imeoer** [comment]
@lepture thks :+1:
