### ISSUE TITLE
linux 下的 spm build 和 windows 下的 spm build 结果为啥不一样涅？

### ISSUE THREAD

**Issue by dragonzu** [spmjs/spm2#23]
linux 下的 spm build 和 windows 下的 spm build 结果为啥不一样涅？

[linux执行如下]
          ......
                  Task: "uglify:js" (uglify) task
                    file: "dist/dialog.js" created.
  uncompressed: size: 8709 bytes.
      compressed: size: 91 bytes gzipped (344 bytes minified).
                    file: "dist/jquery-dialog/5.0.3/jquery-dialog.js" created.
  uncompressed: size: 24084 bytes.
      compressed: size: 2116 bytes gzipped (9114 bytes minified).
                    file: "dist/jquery-dialog/5.0.3/jquery-dialog-plugins.js" created.
  uncompressed: size: 8719 bytes.
      compressed: size: 731 bytes gzipped (3050 bytes minified).
          ......

[windows执行如下]
          ......
                  Task: "uglify:js" (uglify) task
                    file: "dist/dialog.js" created.
  uncompressed: size: 47990 bytes.
      compressed: size: 4096 bytes gzipped (18972 bytes minified).
                    file: "dist/jquery-dialog/5.0.3/jquery-dialog.js" created.
  uncompressed: size: 24084 bytes.
      compressed: size: 2117 bytes gzipped (9114 bytes minified).
                    file: "dist/jquery-dialog/5.0.3/jquery-dialog-plugins.js" created.
  uncompressed: size: 8719 bytes.
      compressed: size: 733 bytes gzipped (3050 bytes minified).
          ......

windows下正常合并压缩了，但linux下没有合并，这是为啥涅？
都用的spm 2.0.3

**Comment by dragonzu** [comment]
问题解决了，package.json的output去掉了要合并的js
（但还是不明白为啥同样的js，同样的package.json，两个系统会出现不同的打包结果）

**Comment by lepture** [comment]
show me the code.
