### ISSUE TITLE
css压缩bug？

### ISSUE THREAD

**Issue by dragonzu** [spmjs/spm2#24]
帮解释下这是不是个BUG
对css文件spm build后 background:url 被改了：1.0.0会变成1.0，5.0.3会变成5.3
如：background:url(http://xxx.cn/test/1.0.0/dialog/5.0.3/images/bg.jpg);
会变成：background:url(http://xxx.cn/test/1.0/dialog/5.3/images/bg.jpg);
为啥涅？

**Comment by lepture** [comment]
I can't reproduce it.

This is not a issue related to spm2.

**Comment by dragonzu** [comment]
你写一个style.css内容就一句话body{background:url(http://xxx.cn/test/1.0.0/dialog/5.0.3/images/bg.jpg);}
然后配个简单的package.json
spm build
看下结果
ps：我用的spm 2.0.3

**Comment by lepture** [comment]
@dragonzu I did it.

**Comment by dragonzu** [comment]
@lepture 
我再抛个bug：文件名带点build时会有错 jquery.tmpl.js
 warn: file .build\src\jquery-debug.tmpl.js not found
貌似跟css那个一个问题

**Comment by lepture** [comment]
@dragonzu the css isssue is related to https://github.com/GoalSmashers/clean-css

現在的版本已經處理好了，需要升級相關依賴，因爲我的是開發版，所以沒有問題，等下周升級後就好了。
