### ISSUE TITLE
spm build 分離

### ISSUE THREAD

**Issue by lepture** [spmjs/spm2#25]
spm 是包管理器，只負責與發行包相關的工作。

spm 是啓動器，負責啓動各個子命令。
## 需要做的事
- [x] 去掉 spm2 中的 spm build
- [x] 去掉 spm2 中的 grunt 依賴
- [x] 新建 spm-grunt，提供 grunt 的調用
- [x] 新建 spm-build，提供 spm build 的功能

**Comment by lifesinger** [comment]
这个我支持

spm build 也保持纯粹，仅支持标准 CMD 的构建

非标准的构建，我来吧，放在 grunt-cmd-build 里

2013/4/10 Hsiaoming Yang notifications@github.com

> spm 是包管理器，只負責與發行包相關的工作。
> 
> spm 是啓動器，負責啓動各個子命令。
> 需要做的事
> -  去掉 spm2 中的 spm build
> -  去掉 spm2 中的 grunt 依賴
> -  新建 spm-grunt，提供 grunt 的調用
> -  新建 spm-build，提供 spm build 的功能
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spmjs/spm2/issues/25
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香
