### ISSUE TITLE
关于spm的文档问题

### ISSUE THREAD

**Issue by xuhuan** [spmjs/spm2#26]
有没有适合新手看的一步一步从0开始的关于spm的系统性的操作说明文档或者已有的相关文档或资料？
seajs关于各个模块的东西还算能理解，可是感觉seajs用grunt来构建和spm打包这方面的资料实在是太少了，网上Google了半天，也没多少有用信息，而且大部分都是英文的。
感觉基于seajs来开发构建和打包方面的学习成本超过seajs本身啊。
有spm和grunt这方面比较好的学习资料的麻烦推荐下，最好是中文的，谢谢了。

**Comment by lepture** [comment]
時間不夠用

**Comment by xuhuan** [comment]
感觉现在资料很少，特别是spm2部分，spm是有wiki了，还能慢慢研究，spm2的就不行了。还有spm deploy的问题，spm的wiki里的方法和现在的版本好像不一样了，又没办法通用了，我刚才试了个把小时了，还没搞定部署在本地，难道 npm install 进来的 spm-deploy 只能部署到服务器？

**Comment by popomore** [comment]
spm2 的 deploy 就是部署到服务器的

**Comment by xuhuan** [comment]
那部署到本地的怎么处理？难道要手动？一个个拷贝到指定目录？

**Comment by hellolibo** [comment]
我觉得先学grunt吧

**Comment by linxq** [comment]
是啊 能不能系统的搞下，现在来看用起来比较复杂。

**Comment by linxq** [comment]
毕竟这个是seajs的延伸大部分还是前端在研究这个地方，nodejs本来就不是熟悉。

**Comment by linxq** [comment]
在做 concat 合并的文件的时候， 如果a.js依赖b.js,b.js依赖于c.js.可以在a的合拼时把c.js合拼下来吗 @xuhuan @lepture @popomore @hellolibo @leoner ，请各位大侠讲解下。

**Comment by hellolibo** [comment]
@linxq 可以的啊，你自己试一遍就知道了

**Comment by linxq** [comment]
//a.js
define(function(require) {
    require('./b');
    console.log(a);
});
// b.js
define(function(require) {
    require('./c');
    console.log(b);
});
// c.js
define(function(require) {
    console.log(c);
});

Gruntfile 为
    concat: {
        all: {
            options: {
              include: 'all',
              // the modules path
              paths: ['web']
            },
            files: {
              // it will include all dependencies
              // demo/all.js demo/relative.js demo/self.js assets/foo.js
              'dest/all.js': ['web/src/a.js']
            }
        }
    }

合并完成 all.js
define([ "./b" ], function(require) {
    require("./b");
    console.log(a);
});

// b.js
define([ "./c" ], function(require) {
    require("./c");
    console.log(b);
});
其中没有c.js的内容。

@hellolibo

**Comment by roshanca** [comment]
确实，现在 `spm build` 完，就不知道该咋整了。。。无法部署到本地，也无法 `publish` 到网上(ಥ_ಥ)

**Comment by lepture** [comment]
@linxq 建议看一下 http://github.github.com/github-flavored-markdown/ 排版好代码。

**Comment by linxq** [comment]
谢谢，你的建议很好。我们回到这个问题上是不是可以依赖合拼 c.js哪。

//a.js

``` javascript
define(function(require) {
    require('./b');
    console.log(a);
});
```

// b.js

``` javascript
define(function(require) {
    require('./c');
    console.log(b);
});
```

// c.js

``` javascript
define(function(require) {
     console.log(c);
});
```

Gruntfile 为

``` javascript
concat: {
     all: {
          options: {
          include: 'all',
          paths: ['web']
      },
     files: {
       'dest/all.js': ['web/src/a.js']
     }
 }

```

合并完成 all.js

``` javascript

//a.js

define([ "./b" ], function(require) {
    require("./b");
    console.log(a);
});

// b.js

define([ "./c" ], function(require) {
    require("./c");
    console.log(b);
});
```

其中没有c.js的内容。

@hellolibo
@lepture

**Comment by lepture** [comment]
@linxq 你需要先 https://github.com/spmjs/grunt-cmd-transport 再 concat

**Comment by linxq** [comment]
恩 问题解决了，是我transport完的文件和concat的需要的a.js不同导致的问题。谢谢 @lepture

**Comment by LeoYuan** [comment]
感觉你们几个人扛起了通用组所有的开源项目， **牛逼** ！~佩服
不过你们还是好好考虑一下人力这个问题，虽然说大家可以出一份力，
但是毕竟大家不可能付出太多心血在 _贡献_ 上，因为我们也有自己的工作要做。
记得开始使用`spm`时，是摸爬滚打一路过来的，当时文档也不齐全，通过跟@leoner的交流，以及阅读部分源码，也算能做事，
今天想切`spm2`，看得我一头雾水，细节先不说，能不能至少给个完整的例子，里边的grunt task可以先不详细解释，没有整体概念的铺述，对使用者的理解、使用都造成巨大的障碍。

**Comment by X-Bird** [comment]
现在 docs.spmjs.org 上已经有两篇比较还可以的grunt构建文档了，但是我有个疑问，因为自己的代码依赖了aralejs，transport之后，concat all 显示找不到 $ 模块 ，找不到，jquery 模块。
去翻arale 里面的模块代码，发现里面即使构建好的模块写的 require('$')，我把它改成模块的路径 require('jquery/jquery/1.10.1/jquery')，concat的时候就不会出现那个提示了。
问一下，这种 alias 配置在 transport 的时候配置就有效，为什么concat 的时候就不能配置 alias ？

**Comment by popomore** [comment]
concat 只有 include:all 的时候才会报错吧，说明要合并的文件找不到，这个警告也是正常的吧。

**Comment by X-Bird** [comment]
@popomore 是的，就是个警告，但是有这个警告的话，include all 就没有意义啦，有办法给concat配置alias吗？

**Comment by popomore** [comment]
为啥呢，arale 是故意不想把 jquery 打包进来的。

**Comment by X-Bird** [comment]
@popomore 至少给用户提供个选择啊，我就想首页除了一个 seajs 的 script 请求，外加一个 业务script 请求，不想再多一个jquery请求，如果可以把 jquery 打包进来，还可以配合百度 fis 的 map.json 做一些自定义的输出啊

**Comment by popomore** [comment]
那你就自己 require 个 jquery 打包进去好了，在页面上再配置下 $ 的 alias。

**Comment by X-Bird** [comment]
@popomore 这个已经明白了，只是arale里面的就得手动改，谢谢～希望seajs越来越好～

**Comment by popomore** [comment]
arale 里面的保留 $ 就可以，在页面上配的 $ 的 alias，这样也不会重复请求的。

**Comment by X-Bird** [comment]
@popomore 对哦！我居然用的map去map到一个已经具备标识的jquery模块上。你这样好多了！thx～八错～～今天有收获～

**Comment by popomore** [comment]
@xuhuan 下个月会开始整理文档，但是个性化的需求还是要用 grunt 完成，spm-build 是建立在我们的解决方案之上的，如果觉得 ok 也可以使用。
