### ISSUE TITLE
需求：不生成-debug文件

### ISSUE THREAD

**Issue by dragonzu** [spmjs/spm2#27]
需求：不生成-debug文件
貌似以前可以通过设置with-debug属性去掉，现在如果实现呢？只能自己写grunt任务吗？

**Comment by lepture** [comment]
@dragonzu https://github.com/spmjs/spm2/issues/25

首先 spm2 将不会做构建工作了，专注于做包管理，与 https://spmjs.org 通讯。

针对你的问题，你所构建的是发行包？是通过 package.json spm build 出来的？

如果是的话，那是必须要有 debug 文件的。如果你既要用 package.json build 出来，又不想要 debug 文件的话，你可以先 build 出来后再删掉 debug 文件。

**Comment by dragonzu** [comment]
哦，我看seajs官网推荐的构建工具也变成了 Grunt ，那看样子 spm 对 seajs 的支持只会当做一个功能来做，而不是专属于seajs的package manager，要做成类似 npm 是这个意思吧？！

**Comment by lepture** [comment]
@dragonzu 是的， spm 不是构建工具，是包管理。

你需要的是：

https://github.com/spmjs/grunt-cmd-transport
https://github.com/spmjs/grunt-cmd-concat
https://github.com/spmjs/spm-build
