### ISSUE TITLE
output 新规则是怎么样的？

### ISSUE THREAD

**Issue by kfpanda** [spmjs/spm2#3]
spm2 的 output 新规则 是否 应该先整理一下。

**Comment by lepture** [comment]
@kfpanda 目前还在 beta 阶段，暂时未定下来。

有一点可以肯定，`output` 将会只有一个规则，spm build 只做标准打包，任何自定义需求，请使用 grunt。

build 请关注 https://github.com/spmjs/grunt-spm-build ， spm build 也是基于 grunt-spm-build 的，只是内置了一套配置文件。

你可能需要了解一下 grunt。

grunt-spm-build 是一个 task 集合，见：https://github.com/spmjs/grunt-spm-build#collection

**Comment by edokeh** [comment]
grunt-spm-build 感觉文档还是缺了点，要翻翻源码才能搞明白

**Comment by lepture** [comment]
@edokeh still on beta.

另外这是一个集合，理论上是去看各个 task 的文档。不过确实需要一份文档来解释 build 的整个过程。

**Comment by lepture** [comment]
@edokeh 如果有时间，可否帮忙写一写文档呢？

**Comment by edokeh** [comment]
@lepture 
如果有能力，肯定愿意贡献文档
不过现在在看的 grunt-spm-build 这块还比较迷糊，比如这个 issue ，该如何自定义 output 规则就还没弄出个头绪
我看你们目前的文档最基础的功能应该都已经覆盖到了，但是跟 Spm 1.x 相比，还是少了不少东西（其实是 Spm2 功能上做了精简对吧？），这块内容我觉得可能将会是文档很重要的部分

**Comment by lepture** [comment]
@edokeh 

`grunt-spm-build` 是一个 task 集合，把这些 task 串起来还是有不小的难度的，我写了一点 [Build Process](https://github.com/spmjs/grunt-spm-build#build-process)。

你需要的是理解 build 的整个过程，然后去看各个 task 的配置，理论上来说可以完成所有的工作了。

spm2 定位为包管理器，只打包特定的一类包（就是发布到 spmjs.org 上的包），所以现在的 output 简化成了一个列表，没什么可配置的。spm2 也是用的 grunt-spm-build 这一个集合，调用的是 `grunt-spm-build/index.js` 里所写的一个生成 grunt config 的方法 `initConfig`。

如果需要自由组合的话，应该看的是各个子 task 的配置，而不是用 grunt-spm-build 里的这个 `initConfig`。

业务上的打包不会由 spm2 来解决，也解决不了。spm2 将只会服务于标准包，任何自定义需求请使用 grunt 加我所写好的 task 加 grunt 本来就有的 task 来完成。

支付宝内部的业务打包也将如此。`spm build` 将会调用 Gruntfile.js 里的 `build` task，见：

http://docs.spmjs.org/en/build#customize-build

另外，支付宝的方案也是公开的：https://github.com/spmjs/spm-alipay-suite

**Comment by lepture** [comment]
@edokeh example on grunt tasks:

https://github.com/spmjs/issue-cases/tree/master/grunt-spm-build-3

**Comment by edokeh** [comment]
没有 Node 背景，研究起来慢。。。不过大致摸出了个轮廓，争取抓紧贡献篇文章

**Comment by twinstony** [comment]
也正在缓慢学习中，期待你的文章@edokeh

**Comment by lepture** [comment]
@edokeh https://github.com/spmjs/docs.spmjs.org/tree/master/docs/contrib
