### ISSUE TITLE
CSS 中引用 spm 包形式 CSS 库的最佳实践？

### ISSUE THREAD

**Issue by pushiming** [spmjs/spm2#33]
## 场景

在应用的某个 page-level css 中，需要引用 spm 源中提交过的底层样式库，比如 alice/base
## 目录结构

如下

```
sea-modules
  - alice
    - base
      - 1.0.0
        - base.css
src
  - pages
    - detail
      - index.css
```
## 问题

我如何保证在 开发状态（引用 src）和 部署状态（引用 dist）下都能成功 `@import` 到 alice/base？
- 根据 #4 中所示使用顶级标识的方式来引用
  
  ``` css
  @import "alice/base/1.0.0/base.css"
  ```
  
  则在 build 后（使用 grunt-cmd-xxx）一切正常，但是这种方式下，开发模式下显然是引用不到文件的……
- 如果使用相对路径的方式来引用，即在 index.css 中
  
  ``` css
  @import "../../../sea-modules/alice/base/1.0.0/base.css"
  ```
  
  在开发状态下自然是毫无问题的，但是在 build 的时候又很不优雅

所以，有没有一个两全其美的方案？

**Comment by afc163** [comment]
可以参照 AliceUI 的静态文档实现方式：http://aliceui.org/button-dropdown/

主要做法是手动引用 src/button-dropdown.css 文件。（相当于 Arale 中的`seajs.use('../src/example')`）

然后文档模板读取 [package.json](https://github.com/aliceui/button-dropdown/blob/master/package.json#L21) 里的 alias 属性来获得它的依赖并`seajs.use`进来，从而载入依赖。

---

上面是目前的做法。

想了一下，其实可以包装下 `seajs.use` 来提前获取 css 文件中的依赖信息（和解析require('xxx')类似），然后自动载入进来。这个后续可以尝试做一个 `seajs-plugin` 来帮助调试样式文件。

**Comment by pushiming** [comment]
@afc163 首先非常感谢详尽的解答……但是说实话这段话真的不大容易看明白，不过大致还是明白了。是否简单来说的处理手段就是：通过一定办法得到依赖信息后，让 seajs 去取
但是，我直观感觉的几个问题是
1. 太依赖于配置。这样造成的后果是：理解困难，实现复杂
2. 在实现机制上觉得是比较曲线救国的做法，换句话说，比较绕。理想的做法是，js 的依赖由 js 完成，css 的依赖由 css 完成，而让 js 去做本来应该是 css 做的事情，感觉不自然，越俎代庖了
3. 上述做法还带了的一个后果就是，原本 css 中的 `@import "button"` 被 404 了。如图
   
   ![404](https://f.cloud.github.com/assets/340307/504941/c2aa9872-bd04-11e2-8f02-556b515daf21.jpg)
   
   如果 button 已经由 seajs 去取，那么 css 中的 `@import` 就变成了预处理性质的代码，上线后应该去除之

我现在想想，觉得还是在 css 中 **使用相对路径** 去 `@import` 最靠谱，不论是开发阶段还是部署阶段都能正常跑，但是缺点是
1. `@import "../../../......"` 这样深层的相对路径实在是太难看了！……好吧其实我想说习惯了之后就还好，不算问题
2. 现在的 grunt-cmd-concat 对 css 的 concat 支持 **不完善**！请见 [issues](https://github.com/spmjs/grunt-cmd-concat/issues?state=open)
   1. CSS `@import` 目前不能支持多层依赖
   2. `@import` 后的 css 中的相对路径未被得到修正

其中，grunt-cmd-concat 的问题非常非常令人蛋疼，希望能尽快解决，否则，只能考虑使用其他 css concat 工具了，诸如我同事写的 [css-combo](https://github.com/daxingplay/css-combo) 及其 [grunt plugin](https://github.com/daxingplay/grunt-css-combo)

谢谢。另外， @lifesinger 玉伯兄有空的话也来看看吧

**Comment by afc163** [comment]
1. 多层依赖我们是支持的，详细见：https://github.com/aliceui/example 。如果你的目录有问题，请在线上放出能重现问题的包。
2. 相对路径我们不修正，一律采用绝对路径。如果有修正相对路径的需求，请自行编写 `grunt task`。

**Comment by pushiming** [comment]
由于沟通成本关系，中间的讨论未在 github 这里进行……

咳咳，截止目前，关于提出的 grunt-cmd-concat 问题的结论是
1. 多层依赖的那个问题，确认是个 bug，修复进行中……
2. 相对路径修正的问题，确认 spm 组不修正，可能后续我自己修改后提交 pr 进来

**Comment by afc163** [comment]
https://github.com/spmjs/grunt-cmd-concat/issues/15
