### ISSUE TITLE
package.json中怎样配置才能指定某个模块不被合并？

### ISSUE THREAD

**Issue by zicjin** [spmjs/spm2#39]
以前有output -> exclude配置

**Comment by lepture** [comment]
不允许这种情况。

**Comment by lepture** [comment]
出现这种情况，它应该被拆成两个。

**Comment by zicjin** [comment]
那像
require("arale/easing-debug");
这种模块默认依然是不被合并的（这和spm1的策略一样）。我怎样才能让它被合并呢？

**Comment by lepture** [comment]
@zicjin 

```
spm build -h
```

There is an `include` option.

```
spm build --include=all
```

**Comment by zicjin** [comment]
很蛋疼，比如我加载了这两个使用顶级路径的模块：
_ = require('gallery/underscore')
Popup = require('arale/popup')

我希望underscore不被合并，而popup能够被合并。难道需要我把popup拷贝至一个相对路径？
如果使用相对路径引用了popup，它所依赖的其他arale模块（使用了顶级路径）会被合并吗？

**Comment by zicjin** [comment]
还有，help里没有指明有哪些include属性值，除了relative、all以外还有其它的吗？

**Comment by lepture** [comment]
@zicjin include is the option for concat: grunt-cmd-concat

spm-build is a pre-configuration for grunt-cmd-transport, grunt-cmd-concat, and many more tasks. 

> spm build is designed to build standard cmd modules.

https://github.com/spmjs/spm-build

You should use a Gruntfile to do the customized build.

**Comment by edokeh** [comment]
这种有个变态的办法，就是通过alias 将普通路径的模块转为顶级标识，这样合并时候就能 exclude 了
