### ISSUE TITLE
内部的spm info，spm install都是拿的走的git:这样的请求么？怎样改为http://的

### ISSUE THREAD

**Issue by jsvii** [spmjs/spm2#42]
好像里面的资源install都是走的git吧
公司网络有代理好像就拿不到这个了，每执行到git clone git://时都报不存在这个端口，请问有方法解决么？

**Comment by jsvii** [comment]
我说得不对么，为什么没有人回答这个问题？？？？

**Comment by popomore** [comment]
install 是 https 的

**Comment by afc163** [comment]
http://www.google.com.hk/search?q=git+%E4%BB%A3%E7%90%86&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:zh-CN:official&client=firefox-beta

**Comment by edokeh** [comment]
spm install 在连不上 yuan 或者在 yuan 上面找不到资源的时候，会从 git 取资源
你的问题解决办法是需要先设置一下HTTP代理

**Comment by popomore** [comment]
@GoodLuckBamboo 这个有帮你解决么
