### ISSUE TITLE
清理下 issue 吧

### ISSUE THREAD

**Issue by afc163** [spmjs/spm2#43]
为了让 @lepture 清理 issue，我建了这个 issue。

**Comment by jiangyuan** [comment]
为了让 @lepture 清理 issue ，我顶顶这个 issue 。

**Comment by popomore** [comment]
<del>- [ ] https://github.com/spmjs/cmd-util/issues/3</del>

**Comment by popomore** [comment]
- [x] https://github.com/spmjs/grunt-cmd-transport/issues/24

**Comment by popomore** [comment]
- [x] https://github.com/spmjs/spm-build/issues/22

**Comment by popomore** [comment]
- [x] https://github.com/spmjs/spm-build/issues/21
