### ISSUE TITLE
文档支持历史版本

### ISSUE THREAD

**Issue by popomore** [spmjs/spm2#45]
publish 文档的时候如果打了 tag，可以查看这个 tag 的内容

**Comment by afc163** [comment]
最好是自动打 tag，每当 publish-doc 时，自动更新 master 和 对应的 tag。

**Comment by popomore** [comment]
已经完成

**Comment by afc163** [comment]
例子可以查看：http://aralejs.org/dialog/

获取功能：安装 spm@2.1.3 版本，并使用 `spm publish --doc _site` 发布一个文档。
