### ISSUE TITLE
还会有 spm transport 吗？

### ISSUE THREAD

**Issue by edokeh** [spmjs/spm2#50]
虽然 Grunt 也能用，但是有些情况下 transport 更方便一点

**Comment by popomore** [comment]
想做，但是外部模块千奇百怪，很多需要修改代码，还没抽象出一个很好模型 https://github.com/spmjs/apm/issues/11

**Comment by afc163** [comment]
@edokeh 有啥想法没，https://github.com/cmdjs/gallery 里面的模块包装方式基本都不太一样，看看有没有什么好方法。（白名单？）

**Comment by edokeh** [comment]
貌似没啥好办法，但是把以前的 transport 弄回来起码能解决 60% 的情况，已经足够了，其他就自己写 Grunt 吧

**Comment by afc163** [comment]
先关了，这个问题来来回回好几个 issue 都不了了之了。
