### ISSUE TITLE
concat 的 css2js 移到 transport 中

### ISSUE THREAD

**Issue by popomore** [spmjs/spm2#54]
现在 css2js 有两部分，功能都是把 css 转换成 js

```
define(function(require) {
  require('poptip');
  require('./poptip.css')
})
```
1. 相对的 css
   
   这部分是在 transport 中做的，会把本地的 poptip.css 转换成 poptip.css.js。
2. 外部的 css
   
   在 transport 中不会处理，在 concat 的时候才会读取文件合并。处理还是会调用 transport 的 css2js 方法。

其实这两部分是可以合并的，代码放在一起便于管理，会比较统一，而且可以公用 transport 的参数。

**Comment by afc163** [comment]
issues-center/issues#1

**Comment by kyfxbl** [comment]
grunt-cmd-concat里的readme.md没刷新呀，还写着css2js选项
