### ISSUE TITLE
为什么代理网络用不了spm install，无法走git协议 

### ISSUE THREAD

**Issue by jsvii** [spmjs/spm2#55]
我工作的地方，网络是有代理的，只能走http和https协议，spm也可以安装的，但是一执行到git clone git:// 这个命令时，就会问题。

我这里git  clone git://something 是走不了的，因为代理网络不能走这个协议。

git clone http://somethin也是可以的，为什么spm内部不这样子做？

**Comment by popomore** [comment]
应该是安装的问题咯，安装时要加 family，如 `spm install gallery/handlebars`

**Comment by afc163** [comment]
spm 的版本可能比较低，原来在找不到模块时，会去猜一个 github 的地址。

新版取消了这个特性，建议升级。

**Comment by edokeh** [comment]
之前看过 spm2 代码，貌似不支持代理
https://github.com/spmjs/spm2/blob/master/lib/sdk/yuan.js#L70
这里虽然有支持，但是外部调用的时候没看到有方式能够传入 proxy 参数

**Comment by jsvii** [comment]
@edokeh  谢谢哈～
这个是不能实现，还是做不到啊？
我的npm 是可以设置代理的。觉得spm这么弄应该不麻烦的，麻烦spm团队支持一下这个性能。

**Comment by edokeh** [comment]
@GoodLuckBamboo 
临时的做法是，可以打开本机上的这个文件直接修改一下这行代码

**Comment by lepture** [comment]
@GoodLuckBamboo @edokeh 改成从环境变量获取？

**Comment by edokeh** [comment]
还是用参数吧，自由一点
