### ISSUE TITLE
spmjs/spm 仓库中的 Wiki 和 spm2 是否有对应?

### ISSUE THREAD

**Issue by tiye** [spmjs/spm2#58]
之前的文档是 outdated 还是已经根据新的 spm2 做了修改呢?
https://github.com/spmjs/spm/wiki/_pages

**Comment by afc163** [comment]
原来的文档已经全部 outdated 了。

**Comment by tiye** [comment]
@afc163 再问下现有的 SPM 可以参考的文档是否有方便直接查找的列表的列表呢?
除了 docs.spm.org 和 spm2 issue 里以外, Google 到的文档有一些, 但并不明白怎么区分是否在 2 可用

**Comment by afc163** [comment]
最新可用的文档就是这个了：http://docs.spmjs.org/

相关的具体应用文档也可以参考 Arale 和 Alice 。

http://aralejs.org/docs/installation.html
http://aralejs.org/docs/develop-components.html
http://aliceui.org/docs/build.html

Google 到的文档，如果出现 spm 1.x.x 的版本（或更低）字样的，则不适用于最新版本。

**Comment by tiye** [comment]
@afc163 Thanks.
