### ISSUE TITLE
jquery-plugin / form install 不了

### ISSUE THREAD

**Issue by billwing** [spmjs/spm2#59]
spm install jquery-plugin/form
为什么这个包install的时候报错了？

**Comment by afc163** [comment]
报什么错？我这里亲测是好的。

**Comment by lepture** [comment]
@afc163 一个 dependency 的问题。

@Billwing Install the new one.

**Comment by billwing** [comment]
呃，还是有问题，是我环境问题？
![spm error](https://f.cloud.github.com/assets/3411815/833106/8c03f034-f28d-11e2-9e96-b6bb4cfe427a.png)

**Comment by billwing** [comment]
@lepture 嗯嗯，现在可以了~
