### ISSUE TITLE
component.json ?

### ISSUE THREAD

**Issue by lepture** [spmjs/spm2#6]
使用 `component.json` 代替 `package.json`

大致字段：

``` json
{
  "family": "arale",
  "name": "base",
  "version": "1.0.0",
  "description": "......",
  "repository": {....},
  "homepage": "...",
  ...
  "alias": {...},
  "main": ["base.js", "i18n/*.js"]
}
```

**Comment by tiye** [comment]
有些担心文件名重复的问题, Bower 用的 `component.json` 就讨论过 https://github.com/twitter/bower/issues/110
似乎还要考虑规范性什么的, 没理清楚

**Comment by lepture** [comment]
https://gist.github.com/skiant/4134821

想了一下，还是维持现状。

**Comment by lifesinger** [comment]
还是用 package.json 吧，spm 的配置不多
