### ISSUE TITLE
Spm2中parent不能用了吗？

### ISSUE THREAD

**Issue by sarike** [spmjs/spm2#63]
在http://docs.spmjs.org/en/package 中也没有看到这个属性的介绍。
是被移除了吗？

**Comment by popomore** [comment]
没有这个功能了

**Comment by sarike** [comment]
为什么会去掉这个功能呢？如果有大量相同的配置，要在每个文件里都配置一次吗？

**Comment by popomore** [comment]
第一，如果使用 parent，这样模块的信息是不完备的，如果发布到源上问题会更多。

其次，package.json 是一个描述文件，一般不会修改的，你可以写个初始化脚本来生成，一点也不麻烦。

**Comment by sarike** [comment]
理解了，spm2是把一个package.json对应一个可以单独发布的模块了
