### ISSUE TITLE
spm2合并js文件的时候只是按照依赖来合并的吗？

### ISSUE THREAD

**Issue by sarike** [spmjs/spm2#66]
项目中原来用的是spm1.7.3，我想升级成spm2
项目中有个package.json在配置output的时候是把好多js文件合并到一个新的文件中去。
我看了下spm2的文档，貌似没有类似的功能，那么在不修改我页面中调用的情况下，我该如何做呢？

**Comment by sarike** [comment]
有办法了，我单独创建这些文件，然后添加对其它文件的依赖。
貌似没有什么问题吧，而且这样不会有种莫名无中生有的感觉。

**Comment by lepture** [comment]
@sarike You got it.
