### ISSUE TITLE
重新整理 spm 文档

### ISSUE THREAD

**Issue by popomore** [spmjs/spm2#69]
经过了近半年的开发，spm2 已经基本成形了，看到很多人已经从 spm1.x 迁移过来，感到很欣慰，但是很多人也遇到了问题，现在准备重新整理文档，最后会呈现在 http://docs.spmjs.org 上。

这个文档主要包括基本使用方式，支付宝的最佳实践，也包括使用 grunt 搭建小型项目。

希望曾经使用过 spm2 的人可以给出你的建议，也希望提供你们在使用的目录结构和配置，可以综合考虑。

---

补充
- [x] 首页介绍（目前是视频）
- [x] 配置及规范
  - 全局配置 spmrc
  - 模块配置 package.json
- [x] 命令行 安装，使用说明，选项
- [x] apm，支付宝工具套件
  - 使用 apm 配合 arale 开发
- [x] 开发指南，提供给 spm 开发者的文档
  - spm node api
  - 开发 plugin
- [ ] 最佳实践（贡献文档）
  - grunt 构建最佳实践
  - 基于 spm-build 扩展构建
  - 基于 grunt 写构建工具
  - 现有的文档
  - 如何在系统中用 spm 进行静态文件开发

---

> 禁止发和本 issue 不相关的内容和问题，会删的哦

**Comment by sarike** [comment]
这个必须顶呀，一直感觉一个比较好的开源项目，能不能成功关键看它有没有好的文档跟社区。
第一次参见工作，第一次接触到如此管理前端代码的工具，真心感觉很不错，希望spm2越来越好用……

**Comment by kfpanda** [comment]
前端开发，正需要这样的工具。

**Comment by afc163** [comment]
需要一篇：《如何在系统中用 spm 进行静态文件开发》

**Comment by popomore** [comment]
@afc163 准备把流程的东西抽出来放一问一答中，其他的如构建之类的还是一起写。

**Comment by lichunqiang** [comment]
@popomore +1
偶的问题可怎么整啊。#73

**Comment by lizzie** [comment]
@popmore apm 的文档可以用 https://github.com/spmjs/apm/blob/master/README.md 这个啊.

**Comment by kfpanda** [comment]
不错，整理的挺清晰的。
