### ISSUE TITLE
安装不上啊！

### ISSUE THREAD

**Issue by nuintun** [spmjs/spm2#7]
![QQ 20130323102737](https://f.cloud.github.com/assets/1730277/293396/832747ee-9361-11e2-9d5c-7233ce6ca813.jpg)
![QQ 20130323102818](https://f.cloud.github.com/assets/1730277/293397/89f3912c-9361-11e2-856c-b4d4c545fb0d.png)

**Comment by lepture** [comment]
ECONNRESET

这应该是被墙了，你需要向方校长提 bug。

**Comment by nuintun** [comment]
@lepture 无语，伤心啊！

**Comment by nuintun** [comment]
@lepture `spm 1.7.6`正式版也报这个错，但确安装成功了。。。

**Comment by lepture** [comment]
@NewtonNiu nonsense. This is not an issue related to spm. Closed.
