### ISSUE TITLE
spm build之后

### ISSUE THREAD

**Issue by lichunqiang** [spmjs/spm2#73]
情形是这样的：
有一个`util`模块，目前`src`下只有一个`util.js`, 没有任何依赖。
经过`spm build`之后在dist下成功生成两个文件。
文件`define`的ID为`{myfamily}/{name}/{version}/xxx`
这个应该是相对sea-modules文件下的吧。那怎么才能把大部署到sea-modules文件下呢。`spm deploy`无法成功。（package.json中我设置了private）
另外一个问题，
如果我不想将自己的模块放到sea-modules文件下，该怎么配置呢。

**Comment by popomore** [comment]
```
spm install .
```

**Comment by lichunqiang** [comment]
@popomore 执行`spm install`无任何输出，文件上也木有改变。
是不是我的package.json配置有问题？

**Comment by popomore** [comment]
后面还有个点哦 :sparkles:

**Comment by afc163** [comment]
看看这个 issue https://github.com/spmjs/spm-build/issues/29

**Comment by lichunqiang** [comment]
@popomore 不好意思，眼花了。这就试。

**Comment by lichunqiang** [comment]
@afc163 非常有帮助的issue！
@popomore 
通过`spm install . ../sea-modules`成功安装到指定目录。
但是问题有出现了。。。
另外一个模块，`hello`中依赖`util`，我在package.json配置`spm.alias.util = '{myfamily}/util/{version}/util'`,当在去执行`spm install .`的时候产生error了。

``` python
 install: myapp/util@1.0.0
   fetch: myapp/util@1.0.0
    yuan: not found
    warn: not in cache
   error: not found
```

这个信息是不是在install的时候发现依赖，然后去yuan上找了，没找到就报错了。可是我这个util是本地的。

**Comment by popomore** [comment]
到 https://spmjs.org/ 注册一个账号，把你之前的 `myapp/util` 模块 publish 上去。

**Comment by lichunqiang** [comment]
mark下，
可以通过`spm install . -g` 加上`-g`这个参数`install the package to ~./.spm/sea-modules`来解决上面的install失败的问题。

**Comment by popomore** [comment]
:+1:  good idea
