### ISSUE TITLE
npm install spm error EACCES

### ISSUE THREAD

**Issue by billwing** [spmjs/spm2#74]
![qq20130809-1](https://f.cloud.github.com/assets/3411815/939030/5a6416e4-010b-11e3-92c7-8da8b3f2bd89.png)

**Comment by afc163** [comment]
是这个问题：http://aralejs.org/docs/installation.html#%E5%8E%BB%E9%99%A4-sudo

**Comment by billwing** [comment]
好的，解决了 :+1:
