### ISSUE TITLE
spm、spm2和apm的异同

### ISSUE THREAD

**Issue by island205** [spmjs/spm2#77]
正在写[HelloSea.js](https://github.com/Bodule/HelloSea.js)这本小书；当写道spm的时候，我本身并没有深入使用过这个工具，读了一些资料，下面是我的一些看法，希望各位大神帮忙看看不对的地方，也希望能够各位大大把自己的想法分享出来：

---
##### spm与spm2

其实之前介绍的spm是其第二个版本[spm2](https://github.com/spmjs/spm2)。spm的第一个版本可以在[这里](https://github.com/spmjs/spm)找到。

spm与spm2同样都是包管理工具，那它们之间有什么不同呢？
- 从定位上，spm2更加强调该工具是一个cmd包管理工具；
- 从提供的用户接口（cmd命令）spm2比起spm更加规范，作为包管理工具，在使用方式和命令都更趋同于npm；
- 在spm2中，构建命令以插件的方式独立出来，并且分层清晰；Transport和Concat分装成了grunt，便于自定义build方式；基于基础的grunt，构建了一个标准的spm-build工具，用于构建标准的cmd模块；
- 与此类似，deploy和init的功能都是以插件的形式提供的；
- 修改了package.json规范。

为什么作者对spm进行了大量的重构？

之所以进行大量的重构，就是为了保持spm作为包管理工具的特征。如npm一般，只指定最少的规范（package.json），提供包管理的命令，但是这个包如何构建，代码如何压缩并不是npm关心的事情。

只有规则简单合理，只定义接口，不关心具体实现，才有更广的实用性。

> spm本身是从业务需求成长起来的一个包管理工具，spm1更多的是一些需求功能的堆砌，而spm2就是对这些功能的提炼，形成一套适用于业界的工具。
##### apm

apm的全称是：

> Alipay package manager

即支付宝的包管理工具。

apm是基于spm的一套专门为支付宝开发的工具集。我们可以这么看，spm2和apm是spm升级后的两个产物，spm2更加专注于包管理和普适性，而apm更加专注于支付宝业务。由于业务细节和规模的不同，apm可能并不适合其他公司所用，所以需要spm2，而又因为支付宝业务的特殊性和基因，必须apm。

---

**Comment by lepture** [comment]
> 代码如何压缩并不是npm关心的事情

这里应该是 `spm` 吧。

> 而又因为支付宝业务的特殊性和基因，必须apm

不一定要用 apm，只是 apm 把所有要用到的插件都打包好了，同时相应的默认配置也为支付宝做了处理，方便内部员工使用，不用再配置了。

**Comment by island205** [comment]
@lepture 在代码和架构层面，spm2有什么变化？

**Comment by popomore** [comment]
spm 和 spm2 在功能上基本是一致的，差异主要是在架构和代码组织上。

spm2 的代码结构比较复杂，不是三言两语能说清楚的，楼主的看法基本上都是我们的想法。
- spm2 更具有可扩展性，可以通过各种组合实现需求（现在相关的文档并不多），而 spm 就只能改代码了。
- spm2 = 一个包管理工具 + 以 grunt 为基础的构建 + 一推 plugin

内部统一使用的方案(apm)，外部支持各种场景(spm2)
