### ISSUE TITLE
模块引用模板文件的问题

### ISSUE THREAD

**Issue by huhm** [spmjs/spm2#79]
src目录下有文件 b.tpl和a.js,其中a.js内容如下：

<pre>
define(function(require,exports,module){
    var strTpl=require("./b.tpl");
});
</pre>

用spm build 生成时, b.tpl 不在dependencies中

<pre>
warn: file .build\src\b.tpl.js not found
</pre>

生成后的a.js文件为: 

<pre>
define("*/*/a",[],function(require,exports,module){
    var strTpl=require("./b.tpl");
});
</pre>

希望得到：

<pre>
define("*/*/a",["./b.tpl"],function(require,exports,module){
    var strTpl=require("./b.tpl");
});
</pre>

要怎么做，才能将正常打包？

**Comment by afc163** [comment]
不知道你的  Gruntfile 是怎么写的。

**Comment by afc163** [comment]
https://github.com/spmjs/grunt-cmd-transport/blob/master/Gruntfile.js#L146

**Comment by popomore** [comment]
看起来是 transport 的时候没有做 tpl 的 transport

**Comment by huhm** [comment]
不是spm build 吗，要自己写Gruntfile吗？话说这个文件在哪里的，我找不到

**Comment by huhm** [comment]
解决了，改了grunt-cmd-transport的Gruntfile.js文件，不过这个是合并了tpl和js文件，不是require.貌似这样就不用require seajs-text插件了。

**Comment by huhm** [comment]
还是有问题，当模块名和模板名相同时，如a.js,a.tpl打包后，dependencies正常的。当两者不同时，dependencies中不存在模板

**Comment by lifesinger** [comment]
dependencies 正常的应该包含 a.js 和 a.tpl.js

**Comment by popomore** [comment]
搞定了？

**Comment by huhm** [comment]
这个暂时没有问题了
https://github.com/spmjs/spm2/issues/85
