### ISSUE TITLE
安装过程一切正常，可是安装完后就是无法运行，报错！！！

### ISSUE THREAD

**Issue by nuintun** [spmjs/spm2#8]
![Noname](https://f.cloud.github.com/assets/1730277/301012/a202a3d6-95b7-11e2-86d2-d5da8919f7a9.jpg)
系统是`server 2003`

**Comment by lepture** [comment]
图上空白，无信息，请使用纯文本。

**Comment by nuintun** [comment]
@lepture 图片死掉了？

**Comment by lepture** [comment]
@NewtonNiu 已经知道问题了，也解决了，暂时不发布，本周发布正式版。可 checkout 源码测试。（主要对 windows 不熟悉，也许还会有 windows 上的各种问题）。

**Comment by nuintun** [comment]
@嗯，windows应该主要是路径上的问题，linux是`/`，windows是`\`。
