### ISSUE TITLE
spm build的输出问题

### ISSUE THREAD

**Issue by ysj** [spmjs/spm2#81]
我想做一个spm命令行工具， 下面是我的代码

var childexec = require('child_progress').exec;
childexec('spm build', function(err, stdout, stderr) {
    console.log(stdout);
});

执行代码后stdout始终不能得到build的输出值， 但在命令行中却可以看到输出结果， 是grunt机制影响的吗？要如何通过node程序来获取build的输出呢？

**Comment by popomore** [comment]
试试调 spm-build
