### ISSUE TITLE
spm search 提示连接超时，出墙后同样的提示 spm info 也一样

### ISSUE THREAD

**Issue by X-Bird** [spmjs/spm2#84]
spm search 提示连接超时，出墙后同样的提示 spm info 也一样

**Comment by lepture** [comment]
@X-Bird 你是不是安装了 apm ? 查看你的 ~/.spm/spmrc

**Comment by X-Bird** [comment]
@lepture 你好，经排查，现在 npm install -g spm 装了之后默认的源变成了 yuan.alipay.im，以前不是的，手动改成spmjs.org就好了，此 issue close掉，阿里你们的文档的太不全了，别人博客的文章比你们的文档还容易看，我几乎都快放弃seajs这块阵营了，构建那块搞死人啊，而且arale的一些模块好臃肿，switchable这种东西自己写也就几十行代码，但如果用你们的这套，打包完几百行啊，晕了～
虽然开发速度上去了，比较看好fis，现在是seajs这边的阵营结合着fis 的一些功能，暂时还算舒服，新人来很方便的就可以指挥让其干一部分的活，比以前好，只要项目构建配置这关把好，开发的人会舒服很多～
希望seajs的生态圈可以健全一些，不过你们确实对业界做出了很大贡献，谢谢你们！

**Comment by afc163** [comment]
确定你是 `npm install -g spm` 而不是 `npm install -g apm` 的，这两者有本质区别。

据我所知，spm 的代码里根本没出现过 yuan.alipay.im 。

**Comment by X-Bird** [comment]
@afc163 你是对的，我装过apm，后来又重复的装了几次spm，后面几次重装spm没让源变回来。。。
刚clone了spm源码下来，sublime cmd+shift+f 搜了一下，确实毛有yuan.alipay.im。
sincerely apologize...

**Comment by afc163** [comment]
它是这样，只要你设置过这个 config ，后面再装就不会给你更改掉。

之前安过 apm 就一直带着了，最近挺多人遇到这个问题。

这边的文档要提醒一下，我刚刚加上了一句话。https://github.com/aralejs/aralejs.org/blob/master/docs/installation.md#%E6%94%AF%E4%BB%98%E5%AE%9D%E5%A5%97%E4%BB%B6
