### ISSUE TITLE
smp build 合并问题

### ISSUE THREAD

**Issue by huhm** [spmjs/spm2#85]
package.json 中spm.output为["a.js","b.js"];
其中a.js require了b.js;
spm build后,产生a.js和b.js文件，为什么a.js文件为a.js和b.js的合并文件？

**Comment by popomore** [comment]
concat 默认会合并相对引用

```
—
```

**Comment by huhm** [comment]
好像之前的版本不是这样的

**Comment by popomore** [comment]
也是这样的，不过你可以用这个 http://docs.spmjs.org/en/package#spm-include

**Comment by afc163** [comment]
spm 1.x.x 的确不是这样的，2.x 改成这样了。

**Comment by huhm** [comment]
include吗？

**Comment by huhm** [comment]
配置include: relative 后，产生新的问题：
output:["a.js","b.js","c.js"]
同一个文件夹下,有a.js,b.js,c.js;
其中a.js和b.js均require("./c");
生成的a.js,b.js文件均包含c.js模块
