### ISSUE TITLE
安装失败, 请问什么原因

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm2#89]
npm install spm -g --verbose

```
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/home/agideo/local/bin/npm',
npm verb cli   'install',
npm verb cli   'spm',
npm verb cli   '-g',
npm verb cli   '--verbose' ]
npm info using npm@1.3.10
npm info using node@v0.10.18
npm verb cache add [ 'spm', null ]
npm verb cache add name=undefined spec="spm" args=["spm",null]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: 'spm',
npm verb parsed url   path: 'spm',
npm verb parsed url   href: 'spm' }
npm verb lock spm /home/agideo/.npm/e03f10fa-spm.lock
npm verb addNamed [ 'spm', '' ]
npm verb addNamed [ null, '*' ]
npm verb lock spm@ /home/agideo/.npm/2f211a58-spm.lock
npm verb url raw spm
npm verb url resolving [ 'http://registry.npmjs.org/', './spm' ]
npm verb url resolved http://registry.npmjs.org/spm
npm info trying registry request attempt 1 at 07:25:06
npm verb etag "CQJE203WHUF3FE0RED89XX501"
npm http GET http://registry.npmjs.org/spm
npm http 304 http://registry.npmjs.org/spm
npm verb etag spm from cache
npm verb addNamed [ 'spm', '2.1.12' ]
npm verb addNamed [ '2.1.12', '2.1.12' ]
npm verb lock spm@2.1.12 /home/agideo/.npm/f4a0b0ba-spm-2-1-12.lock
npm info install spm@2.1.12 into /home/agideo/local/lib
npm info installOne spm@2.1.12
npm info /home/agideo/local/lib/node_modules/spm unbuild
npm verb tar unpack /home/agideo/.npm/spm/2.1.12/package.tgz
npm verb lock tar:///home/agideo/local/lib/node_modules/spm /home/agideo/.npm/396e17d4-gideo-local-lib-node-modules-spm.lock
npm verb lock tar:///home/agideo/.npm/spm/2.1.12/package.tgz /home/agideo/.npm/c14101a7-gideo-npm-spm-2-1-12-package-tgz.lock
npm info preinstall spm@2.1.12
npm verb unsafe-perm in lifecycle true

> spm@2.1.12 preinstall /home/agideo/local/lib/node_modules/spm
> node scripts/preinstall.js


NO SUDO PLEASE!!!
Maybe you need run:

$ sudo chown -R $USER /usr/local

More information on http://howtonode.org/introduction-to-npm
npm info spm@2.1.12 Failed to exec preinstall script
npm info /home/agideo/local/lib/node_modules/spm unbuild
npm info preuninstall spm@2.1.12
npm info uninstall spm@2.1.12
npm verb true,/home/agideo/local/lib/node_modules,/home/agideo/local/lib/node_modules unbuild spm@2.1.12
npm verb /home/agideo/local/bin,[object Object] binRoot
npm info postuninstall spm@2.1.12
npm ERR! weird error 1
npm verb exit [ 1, true ]
npm ERR! not ok code 0
```

我重新安装过nodejs, 用一下方式

```
echo 'export PATH=$HOME/local/bin:$PATH' >> ~/.bashrc
. ~/.bashrc
mkdir ~/local
mkdir ~/node-latest-install
cd ~/node-latest-install
curl http://nodejs.org/dist/node-latest.tar.gz | tar xz --strip-components=1
./configure --prefix=~/local
make install # ok, fine, this step probably takes more than 30 seconds...
curl https://npmjs.org/install.sh | sh
```

lsb_release  -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:    12.04
Codename:   precise
```

已经删除apt-get 的 nodejs

**Comment by alvin2ye** [comment]
```
sudo chown -R $USER /usr/local
```

也执行过

**Comment by popomore** [comment]
启动 node，然后打印 process.env.SUDO_USER 看看，怀疑是系统权限问题。

看 https://github.com/spmjs/spm2/blob/master/scripts/preinstall.js

**Comment by alvin2ye** [comment]
> console.info(process.env.SUDO_USER)
> undefined

---

> process.env
> { SHELL: '/bin/bash',
>   TERM: 'xterm',
>   SSH_CLIENT: '10.0.2.2 63005 22',
>   SSH_TTY: '/dev/pts/0',
>   LC_ALL: 'C',
>   USER: 'agideo',
>   LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arj=01;31:_.taz=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lz=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.war=01;31:_.ear=01;31:_.sar=01;31:_.rar=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.webm=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.axv=01;35:_.anx=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=00;36:_.au=00;36:_.flac=00;36:_.mid=00;36:_.midi=00;36:_.mka=00;36:_.mp3=00;36:_.mpc=00;36:_.ogg=00;36:_.ra=00;36:_.wav=00;36:_.axa=00;36:_.oga=00;36:_.spx=00;36:_.xspf=00;36:',
>   PATH: '/home/agideo/local/bin:/home/agideo/local/bin:/home/agideo/local/bin:/home/agideo/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games',
>   MAIL: '/var/mail/agideo',
>   PWD: '/home/agideo',
>   LANG: 'en_US',
>   HOME: '/home/agideo',
>   SHLVL: '2',
>   LOGNAME: 'agideo',
>   LC_CTYPE: 'zh_CN.UTF-8',
>   SSH_CONNECTION: '10.0.2.2 63005 10.0.2.15 22',
>   LESSOPEN: '| /usr/bin/lesspipe %s',
>   LESSCLOSE: '/usr/bin/lesspipe %s %s',
>   _: '/home/agideo/local/bin/node',
>   OLDPWD: '/home/vagrant' }

**Comment by popomore** [comment]
理解不能了，那为什么 npm 安装的时候 process.env.SUDO_USER 存在

**Comment by afc163** [comment]
```
npm install spm -g -f 
```

可能是本地有缓存。

**Comment by alvin2ye** [comment]
@afc163 确实是，搞定了，我的青春啊，谢谢
@popomore 谢谢
