### ISSUE TITLE
linux和window下build报错啊！

### ISSUE THREAD

**Issue by nuintun** [spmjs/spm2#9]
![Noname](https://f.cloud.github.com/assets/1730277/307578/0f34b272-96c7-11e2-874d-5c1ff70c88af.jpg)

**Comment by nuintun** [comment]
window测试也是报这个错

**Comment by lepture** [comment]
@NewtonNiu 下次可否不要发图？把 log 发出来就好了。

http://docs.spmjs.org/en/package

**Comment by nuintun** [comment]
@lepture ok~

**Comment by nuintun** [comment]
@lepture 

```
newton@Newton-VirtualBox:~/spm/base/json/1.0.0$ spm -v

  error: unknown option `-v'

newton@Newton-VirtualBox:~/spm/base/json/1.0.0$ spm build

      transport: src/json.js -> .build/src/json.js
   warning: Cannot read property 'id' of undefined Use --force to continue.
Aborted due to warnings.
newton@Newton-VirtualBox:~/spm/base/json/1.0.0$ spm build --force

  error: unknown option `--force'

newton@Newton-VirtualBox:~/spm/base/json/1.0.0$ 
```

什么情况，`unknown option`，版本都看不了！

**Comment by lepture** [comment]
@NewtonNiu http://docs.spmjs.org/

首先，你什么都不用做呀。直接输入 `spm` 就好了。另外，看版本是 `spm -V` 或者 `spm --version`

`-v` 在 unix 里一般指 `--verbose`。

**Comment by nuintun** [comment]
@lepture 测试代码`publish`服务器上了，怎么删除。。。囧！

**Comment by lepture** [comment]
@NewtonNiu 不是你自己账户下的，你不能删。不用理会，还没正式开张，明后天开张后就需要登录才能发布。

**Comment by nuintun** [comment]
恩，明了～
