### ISSUE TITLE
npm install spm-init -g 出错

### ISSUE THREAD

**Issue by ustccjw** [spmjs/spm2#90]
> spm-init@0.4.7 postinstall /home/ustccjw/Downloads/node-v0.10.18-linux-x86/lib/node_modules/spm-init
> node scripts/post-install.js

execvp(): No such file or directory

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

**Comment by ustccjw** [comment]
编译node安装在/usr/local下还是不行

> spm-init@0.4.7 postinstall /usr/local/lib/node_modules/spm-init
> node scripts/post-install.js

execvp(): No such file or directory

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

**Comment by ustccjw** [comment]
spm -V 
2.1.12

**Comment by afc163** [comment]
try 

```
npm update npm -g
```

**Comment by ustccjw** [comment]
原因已找到   没install git...  但是spm-build能intall成功，建议在文档上注明
