### ISSUE TITLE
放宽模块名的字符限制

### ISSUE THREAD

**Issue by edokeh** [spmjs/spm2#92]
目前模块 ID 规则是 /a-zA-Z0-9-/
我觉得可以放宽，增加点（.），下划线（_）等字符
#86

**Comment by popomore** [comment]
这个暂时放着，代码比较乱，而且源里面也有逻辑在，整理下代码再看。

可以先讨论放宽的必要性 @lifesinger @afc163

**Comment by edokeh** [comment]
肯定的的，先讨论清楚了再动嘛
所以，之前为啥不允许点和下划线呢？
我猜测不允许点是因为早期 spm 是这么玩的 `spm install gallery.jquery`，允许点就会有冲突
而不允许下划线实在想不出原因

**Comment by afc163** [comment]
. 和 _ 不支持应该是 Arale 的模块命名规则，我觉得不应该放到 spmjs 的生态圈里来。

**Comment by tiye** [comment]
`spm publish` 带 `.` 的包成功, `spm install` 失败了, `spm info` 也失败的.. 现场:
https://spmjs.org/jiyinyiyong/jquery.scrollTo/

```
➤➤ spm install "jiyinyiyong/jquery.scrollTo"

/usr/local/lib/node_modules/spm/node_modules/cmd-util/lib/iduri.js:20
  var family = m[1] || '';
                ^
TypeError: Cannot read property '1' of null
    at Object.exports.resolve (/usr/local/lib/node_modules/spm/node_modules/cmd-util/lib/iduri.js:20:17)
    at /usr/local/lib/node_modules/spm/lib/install.js:71:20
    at q.process (/usr/local/lib/node_modules/spm/node_modules/async/lib/async.js:608:21)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by afc163** [comment]
http://docs.spmjs.org/doc/package#family-required

**Comment by tiye** [comment]
看上边似乎这没定下来呢.. 是在 publish 时提示命名出错还是在 install 时候兼容特殊符号...

**Comment by tiye** [comment]
我还是先问下怎么删掉吧, 删不掉... `unpublish` 会遇到上边那个报错

**Comment by afc163** [comment]
的确不统一，等待下修复版本吧。先放着也没事。:smile:

**Comment by afc163** [comment]
统计下目前代码中涉及到 name 的命名规范的代码：
1. `publish` https://github.com/spmjs/spm2/blob/master/lib/publish.js#L36
2. `info` `install` `unpublish` https://github.com/spmjs/cmd-util/blob/master/lib/iduri.js#L17

这里 popomore 已经在 publish 时做了校验。https://github.com/spmjs/spm2/commit/203e1effdafc6178054c2ce1db32234edaaa37d6

**Comment by afc163** [comment]
然后不支持的 `.` 的原因是现在的用法依然支持 `spm install arale.base` 这样的旧用法，属于照顾过去的习惯。

不支持 `_` 是因为太丑。倾向于保持现状。

**Comment by edokeh** [comment]
> 是因为太丑
> 是因为太丑
> 是因为太丑
> 是因为太丑
> 是因为太丑

:-1: :-1: :-1: :-1: :-1:

**Comment by tiye** [comment]
`arale.base` 是一个包名是吧, 而不是特殊语法?

相比如果遇到奇葩场景需要用到 `_` 了, 可又因为太丑给屏蔽了.. 宁可丑一点.

**Comment by afc163** [comment]
`arale.base` 应该是和 `arale/base` 同义。 这是个历史原因。

**Comment by edokeh** [comment]
我心爱的 `_` 就这么被判了死刑 :cry: 
嫌 `_` 丑敢不敢不用 underscore ！

**Comment by afc163** [comment]
。。

**Comment by popomore** [comment]
component 也推荐这样写 https://github.com/component/component/wiki/Building-better-components#naming-conventions
