### ISSUE TITLE
执行spm-build时能否不自动下载依赖生成文件夹

### ISSUE THREAD

**Issue by ghost** [spmjs/spm2#94]
Task: "clean:build" (clean) task

Task: "spm-install" task

install: gallery/json@1.0.2
          fetch: gallery/json@1.0.2
        extract: ~/.spm/cache/gallery/json/1.0.2/json-1.0.2.tar.gz
          found: dist in the package
      installed: sea-modules/gallery/json/1.0.2

目前工程中有多模块，都依赖于
"json": "gallery/json/1.0.2/json.js"
spm-build时会自动下载json包，这样每个模块文件夹中都有了一个sea-modules/gallery/json/1.0.2这样的文件夹。
但是我的模块不一定布在sea-modules下面。
而且他们应该有一个公共的库。
有没有办法build时不生成这个文件夹。

**Comment by afc163** [comment]
这个文件夹只是用于构建，可以不需要实际部署，你当看不见好了。

**Comment by ghost** [comment]
只用于构建的话
即使不存在也应该可以能够执行build，
现在即使有些依赖不存在也能build成功，只是抛出warning。
spm install的时候会检查依赖关系，失败会报错，下载相应的依赖模块应该放到这个动作中吧。
或者build的时候能否指定sea-modules的目录。

**Comment by popomore** [comment]
你可以自己指定 gruntfile，然后自定义 task，把 spm-install 去掉。

修改 ~/.spm/spmrc

```
[user]
gruntfile = path/to/Gruntfile.js
```
