### ISSUE TITLE
请问spm和npm有什么区别呢？

### ISSUE THREAD

**Issue by kyfxbl** [spmjs/spm2#95]
hi，看了readme.md，我才知道spm是一个package manager，而不是一个build tool。但是我不明白，包管理器已经有了npm，spm有什么区别呢？

**Comment by afc163** [comment]
node 端和浏览器端的区别。

**Comment by kyfxbl** [comment]
但是spm需要依托于node执行是吗？

**Comment by afc163** [comment]
是的，spm 就是 node 下的一个工具。负责浏览器端的包管理。

**Comment by kyfxbl** [comment]
谢谢，稍微清晰一点了，再理解一下。。
node有npm，seajs又有spm，这2天信息太密集，头实在很晕，呵呵，谢谢afc163
