### ISSUE TITLE
SPM 可否增加 npm 和 Bower 中命令行一些习惯?

### ISSUE THREAD

**Issue by tiye** [spmjs/spm2#97]
比较顺的几个是

```
npm install --save package
npm install --save-dev package
npm install list
npm init

bower install --save package
bower install --save package
bower install list
bower init
```

`search` 和 `info` 是已经有的,
`init` 我个人感觉是生成 `package.json`, 但 SPM 依赖 `Makefile` 似乎就不能限于那样的功能..
关于 `--save` 目前 `SPM` 在 `install` 同时没有发现写 `dependencies`.. 手写比较麻烦,
`list` 有看到 `tree` 命令对应.. 但是没看懂,, 是读 `package.json` 的数据吗?

我个人用 npm 和 Bower 比较多, 比较希望相关命令能一致. 个人观点.

**Comment by afc163** [comment]
`npm install spm-init -g`

你就可以用 `spm init` 了。

**Comment by afc163** [comment]
`--save` 和 `--save-dev` 可以加上。

**Comment by tiye** [comment]
`init` 文档有写, 知道的, 我问题里是 `init` 功能过多了, 可能就开始对文件进行重写.. 不够灵活.
或者干脆说当我开发的习惯并不和 SPM 模板里一致时感到有点郁闷..
可能是两个问题,
1. SPM 对 Makefile 的依赖有多重, Makefile 功能直接由 SPM 执行有没有可能?
2. 比如只有 `package.json` 文件是 SPM 生成的, 其他的文件都不管(放到模板去, 但不默认使用).
   那这时是否要求 `src/` 下的目录和 `name` 对应, 因为 `package.json` 没有对应 Bower 的 `main` 字段?

**Comment by popomore** [comment]
可以重新写个模板，或者使用 grunt 的模板

**Comment by tiye** [comment]
@popomore 如果长些很多小项目, 习惯代码模块化, 而不推荐用模板呢?

**Comment by popomore** [comment]
我是说 init 有模板的，每个小项目初始化都是按照这个模板，因为 arale 的模板无法满足你

**Comment by afc163** [comment]
现在可以不使用 Makefile，所有的功能基本可以由 spm 来完成。

**Comment by tiye** [comment]
已经集成在 SPM 里了? 那现在的 Makefile 是怎么, 没有调用吗?

**Comment by afc163** [comment]
像 https://github.com/aralejs/tip 这个，都删掉了 Makefile，其他的也都没调用了。基本命令就是：

```
spm build
spm publish
spm doc build
spm doc watch
spm doc publish
spm test
spm totoro
```

这几个，我们都集成到 [apm](https://github.com/spmjs/apm) 里面了。

**Comment by tiye** [comment]
看本地的 `Makefile` 也的确是调用了 SPM 的命令.. 并且编译过程也没用过 `make`.
奇怪那这样不是没必要生成 `Makefile` 文件了么, 这个完全在 SPM 能搞定的
