### ISSUE TITLE
发到 SPM 的 package 必须要编译吗?

### ISSUE THREAD

**Issue by tiye** [spmjs/spm2#98]
主要是文档没写.. 而且觉得编译的代码我一般都 `.gitignore` 算了... 编译到 `dist/` 是否是必要的?

**Comment by lizzie** [comment]
spm publish 之前需要 spm build , 最终 publish 的代码就是 dist/ 目录和 package.json

**Comment by tiye** [comment]
比如我引用了 `zepto/zepto/1.0.0/zepto`, seajs 是用的 `dist/` 下的文件吗?

**Comment by lizzie** [comment]
是的.
