### ISSUE TITLE
ubuntu 下安装出错了，什么情况呢？ 新手求教

### ISSUE THREAD

**Issue by senomorii** [spmjs/spm2#99]
npm http GET https://registry.npmjs.org/spm
npm http 304 https://registry.npmjs.org/spm

> spm@2.2.0 preinstall /usr/lib/node_modules/spm
> node scripts/preinstall.js

NO SUDO PLEASE!!!
Maybe you need run:

$ sudo chown -R $USER /usr/local

More information on http://howtonode.org/introduction-to-npm
npm ERR! spm@2.2.0 preinstall: `node scripts/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spm@2.2.0 preinstall script.
npm ERR! This is most likely a problem with the spm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/preinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls spm
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.0-12-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "spm"
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.13
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR! not ok code 0

**Comment by edokeh** [comment]
#83

**Comment by lizzie** [comment]
thanks @edokeh

**Comment by senomorii** [comment]
还是有错误的呢。
yun@ubuntu:/home$ npm install -g spm
npm http GET https://registry.npmjs.org/spm
npm http 200 https://registry.npmjs.org/spm
npm http GET https://registry.npmjs.org/spm/-/spm-2.2.0.tgz
npm http 200 https://registry.npmjs.org/spm/-/spm-2.2.0.tgz
npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/spm'
npm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/spm']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/lib/node_modules/spm',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/lib/node_modules/spm',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.11.0-12-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "spm"
npm ERR! cwd /home
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path /usr/lib/node_modules/spm
npm ERR! fstream_path /usr/lib/node_modules/spm
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/lib/node_modules/spm'
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.11.0-12-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "spm"
npm ERR! cwd /home
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/npm-debug.log
npm ERR! not ok code 0

**Comment by afc163** [comment]
不能完整的读一下 #83 和里面的相关链接么？

**Comment by afc163** [comment]
try `npm install spm -gf`，升级到 2.2.2，我删掉了 autoupdate 的逻辑，这个引起了不少问题。
